### ISSUE TITLE
Result reproducible on cifar10

### ISSUE THREAD

**Issue by khawar-islam** [hzlsaber/IPMix#2]
Dear @hzlsaber 

Thanks for your code and help. I reproduced the cifar10 results based on your code, If you can explain or give some useful insights, I didn't change anything in your code. 

**Did you report the Clean Error based on the last epoch of training which is Test Error 4.04, it matches with the paper. Am I right?** I read your paper briefly where you mentioned that "Mean and standard derivation over three random seeds is shown for each experiment". I just want to clarify it 

**In Table 4, the CIFAR results of IPMix is 8.6, and in the below log, I got Mean C Corruption Error: 8.852. Am I right?**

**We also evaluated the IPMix on CIFAR10-C-Bar, I didn't find the results in the paper but I have seen them in your code. Am I missing something?**

**Results**

```
Epoch  99 | Time    79 | Train Loss 0.3130 | Test Loss 0.134 | Test Error 3.95
Epoch 100 | Time    78 | Train Loss 0.3105 | Test Loss 0.134 | Test Error 4.04
Adversarial Test Error: 74.920

gaussian_noise	Test Loss 0.287 | Test Error 9.432
shot_noise	Test Loss 0.240 | Test Error 7.904
impulse_noise	Test Loss 0.299 | Test Error 9.726
defocus_blur	Test Loss 0.196 | Test Error 6.236
glass_blur	Test Loss 0.442 | Test Error 14.384
motion_blur	Test Loss 0.274 | Test Error 8.898
zoom_blur	Test Loss 0.231 | Test Error 7.194
snow	Test Loss 0.272 | Test Error 8.850
frost	Test Loss 0.222 | Test Error 7.230
fog	Test Loss 0.216 | Test Error 6.744
brightness	Test Loss 0.153 | Test Error 4.844
contrast	Test Loss 0.181 | Test Error 5.698
elastic_transform	Test Loss 0.298 | Test Error 9.534
pixelate	Test Loss 0.574 | Test Error 15.812
jpeg_compression	Test Loss 0.312 | Test Error 10.296
Mean C Corruption Error: 8.852

blue_noise_sample	Test Loss 0.425 | Test Error 14.072
brownish_noise	Test Loss 0.484 | Test Error 15.820
checkerboard_cutout	Test Loss 0.279 | Test Error 9.070
inverse_sparkles	Test Loss 0.764 | Test Error 22.532
pinch_and_twirl	Test Loss 0.242 | Test Error 7.594
ripple	Test Loss 0.403 | Test Error 12.176
circular_motion_blur	Test Loss 0.191 | Test Error 6.066
lines	Test Loss 0.472 | Test Error 14.962
sparkles	Test Loss 0.385 | Test Error 12.574
transverse_chromatic_abberation	Test Loss 0.516 | Test Error 16.722
Mean C-Bar Corruption Error: 13.159

Mean Corruption Error: 10.575
```

**Comment by hzlsaber** [comment]
Hi, thank you for your reaching out.

1-2: I think you get the right result. Since IPMix will randomly choose images to mix and generate new image, it may create more **diverse** images compared to other data augmentation methods. In my experiments, I get the worst result in CIFAR-10-C with WRN-40x4 is 8.74 (More than 3 attempts), but I consider what you did is right.

Here is my log. The result is **8.628**.

Epoch  98 | Time    86 | Train Loss 0.2580 | Test Loss 0.127 | Test Error 4.04
Epoch  99 | Time    86 | Train Loss 0.2521 | Test Loss 0.127 | Test Error 4.01
Epoch 100 | Time    86 | Train Loss 0.2562 | Test Loss 0.127 | Test Error 4.09
Adversarial Test Error: 74.490

gaussian_noise	Test Loss 0.282 | Test Error 9.212
shot_noise	Test Loss 0.239 | Test Error 7.892
impulse_noise	Test Loss 0.254 | Test Error 8.224
defocus_blur	Test Loss 0.188 | Test Error 6.154
glass_blur	Test Loss 0.431 | Test Error 14.230
motion_blur	Test Loss 0.267 | Test Error 8.794
zoom_blur	Test Loss 0.230 | Test Error 7.296
snow	Test Loss 0.255 | Test Error 8.344
frost	Test Loss 0.215 | Test Error 7.046
fog	Test Loss 0.203 | Test Error 6.454
brightness	Test Loss 0.145 | Test Error 4.788
contrast	Test Loss 0.171 | Test Error 5.526
elastic_transform	Test Loss 0.294 | Test Error 9.442
pixelate	Test Loss 0.603 | Test Error 15.766
jpeg_compression	Test Loss 0.308 | Test Error 10.250
Mean C Corruption Error: 8.628

3: We do did experiment on CIFAR-C-Bar, but we only reported the results with WRN-40x4. The result on CIFAR-10-C-Bar is 13.04. Therefore, I believe that your result is within the range of error.

The result of CIFAR-10-C-Bar is in Table 13. You can read some information from here: https://arxiv.org/abs/2310.04780

Besides, I must say that I don't think IPMix is perfect. If you find a better mixing method or more effective synthetic data, feel free to let us know at any time.

Good luck!

(The results of CIFAR-10-C-Bar are in Appendix, if I forget to refer to.)

**Comment by khawar-islam** [comment]
@hzlsaber thank you for your comprehensive answer. I am working on it and let you know
